/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedBenefitsRouteImport } from './routes/_authenticated/benefits'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDataTransferRouteImport } from './routes/_authenticated/data-transfer'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedEntitiesRouteImport } from './routes/_authenticated/entities'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedHrAccountsRouteImport } from './routes/_authenticated/hr-accounts'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOrgRouteImport } from './routes/_authenticated/org'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRecruitmentRouteImport } from './routes/_authenticated/recruitment'
import { Route as AuthenticatedSalaryRouteImport } from './routes/_authenticated/salary'
import { Route as AuthenticatedSeparationRouteImport } from './routes/_authenticated/separation'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTimesheetsRouteImport } from './routes/_authenticated/timesheets'
import { Route as ApiActionableApprovalRouteImport } from './routes/api/actionable/approval'
import { Route as OauthOutlookReturnRouteImport } from './routes/oauth/outlook/return'
import { Route as OauthTeamsReturnRouteImport } from './routes/oauth/teams/return'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenefitsRoute = AuthenticatedBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataTransferRoute =
  AuthenticatedDataTransferRouteImport.update({
    id: '/data-transfer',
    path: '/data-transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntitiesRoute = AuthenticatedEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrAccountsRoute = AuthenticatedHrAccountsRouteImport.update({
  id: '/hr-accounts',
  path: '/hr-accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgRoute = AuthenticatedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruitmentRoute =
  AuthenticatedRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryRoute = AuthenticatedSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeparationRoute = AuthenticatedSeparationRouteImport.update({
  id: '/separation',
  path: '/separation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimesheetsRoute = AuthenticatedTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiActionableApprovalRoute = ApiActionableApprovalRouteImport.update({
  id: '/api/actionable/approval',
  path: '/api/actionable/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthOutlookReturnRoute = OauthOutlookReturnRouteImport.update({
  id: '/oauth/outlook/return',
  path: '/oauth/outlook/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTeamsReturnRoute = OauthTeamsReturnRouteImport.update({
  id: '/oauth/teams/return',
  path: '/oauth/teams/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-transfer': typeof AuthenticatedDataTransferRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/entities': typeof AuthenticatedEntitiesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr-accounts': typeof AuthenticatedHrAccountsRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/org': typeof AuthenticatedOrgRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/separation': typeof AuthenticatedSeparationRoute
  '/team': typeof AuthenticatedTeamRoute
  '/timesheets': typeof AuthenticatedTimesheetsRoute
  '/api/actionable/approval': typeof ApiActionableApprovalRoute
  '/oauth/outlook/return': typeof OauthOutlookReturnRoute
  '/oauth/teams/return': typeof OauthTeamsReturnRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-transfer': typeof AuthenticatedDataTransferRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/entities': typeof AuthenticatedEntitiesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr-accounts': typeof AuthenticatedHrAccountsRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/org': typeof AuthenticatedOrgRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/separation': typeof AuthenticatedSeparationRoute
  '/team': typeof AuthenticatedTeamRoute
  '/timesheets': typeof AuthenticatedTimesheetsRoute
  '/api/actionable/approval': typeof ApiActionableApprovalRoute
  '/oauth/outlook/return': typeof OauthOutlookReturnRoute
  '/oauth/teams/return': typeof OauthTeamsReturnRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/benefits': typeof AuthenticatedBenefitsRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-transfer': typeof AuthenticatedDataTransferRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/entities': typeof AuthenticatedEntitiesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/hr-accounts': typeof AuthenticatedHrAccountsRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/org': typeof AuthenticatedOrgRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recruitment': typeof AuthenticatedRecruitmentRoute
  '/_authenticated/salary': typeof AuthenticatedSalaryRoute
  '/_authenticated/separation': typeof AuthenticatedSeparationRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/timesheets': typeof AuthenticatedTimesheetsRoute
  '/api/actionable/approval': typeof ApiActionableApprovalRoute
  '/oauth/outlook/return': typeof OauthOutlookReturnRoute
  '/oauth/teams/return': typeof OauthTeamsReturnRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/request-access'
    | '/reset-password'
    | '/attendance'
    | '/benefits'
    | '/compliance'
    | '/dashboard'
    | '/data-transfer'
    | '/employees'
    | '/entities'
    | '/expenses'
    | '/finance'
    | '/hr-accounts'
    | '/learning'
    | '/leave'
    | '/onboarding'
    | '/org'
    | '/payroll'
    | '/performance'
    | '/policies'
    | '/profile'
    | '/recruitment'
    | '/salary'
    | '/separation'
    | '/team'
    | '/timesheets'
    | '/api/actionable/approval'
    | '/oauth/outlook/return'
    | '/oauth/teams/return'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/request-access'
    | '/reset-password'
    | '/attendance'
    | '/benefits'
    | '/compliance'
    | '/dashboard'
    | '/data-transfer'
    | '/employees'
    | '/entities'
    | '/expenses'
    | '/finance'
    | '/hr-accounts'
    | '/learning'
    | '/leave'
    | '/onboarding'
    | '/org'
    | '/payroll'
    | '/performance'
    | '/policies'
    | '/profile'
    | '/recruitment'
    | '/salary'
    | '/separation'
    | '/team'
    | '/timesheets'
    | '/api/actionable/approval'
    | '/oauth/outlook/return'
    | '/oauth/teams/return'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/request-access'
    | '/reset-password'
    | '/_authenticated/attendance'
    | '/_authenticated/benefits'
    | '/_authenticated/compliance'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-transfer'
    | '/_authenticated/employees'
    | '/_authenticated/entities'
    | '/_authenticated/expenses'
    | '/_authenticated/finance'
    | '/_authenticated/hr-accounts'
    | '/_authenticated/learning'
    | '/_authenticated/leave'
    | '/_authenticated/onboarding'
    | '/_authenticated/org'
    | '/_authenticated/payroll'
    | '/_authenticated/performance'
    | '/_authenticated/policies'
    | '/_authenticated/profile'
    | '/_authenticated/recruitment'
    | '/_authenticated/salary'
    | '/_authenticated/separation'
    | '/_authenticated/team'
    | '/_authenticated/timesheets'
    | '/api/actionable/approval'
    | '/oauth/outlook/return'
    | '/oauth/teams/return'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RequestAccessRoute: typeof RequestAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiActionableApprovalRoute: typeof ApiActionableApprovalRoute
  OauthOutlookReturnRoute: typeof OauthOutlookReturnRoute
  OauthTeamsReturnRoute: typeof OauthTeamsReturnRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benefits': {
      id: '/_authenticated/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof AuthenticatedBenefitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-transfer': {
      id: '/_authenticated/data-transfer'
      path: '/data-transfer'
      fullPath: '/data-transfer'
      preLoaderRoute: typeof AuthenticatedDataTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entities': {
      id: '/_authenticated/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AuthenticatedEntitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr-accounts': {
      id: '/_authenticated/hr-accounts'
      path: '/hr-accounts'
      fullPath: '/hr-accounts'
      preLoaderRoute: typeof AuthenticatedHrAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org': {
      id: '/_authenticated/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedOrgRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruitment': {
      id: '/_authenticated/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedRecruitmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary': {
      id: '/_authenticated/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AuthenticatedSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/separation': {
      id: '/_authenticated/separation'
      path: '/separation'
      fullPath: '/separation'
      preLoaderRoute: typeof AuthenticatedSeparationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timesheets': {
      id: '/_authenticated/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof AuthenticatedTimesheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/actionable/approval': {
      id: '/api/actionable/approval'
      path: '/api/actionable/approval'
      fullPath: '/api/actionable/approval'
      preLoaderRoute: typeof ApiActionableApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/outlook/return': {
      id: '/oauth/outlook/return'
      path: '/oauth/outlook/return'
      fullPath: '/oauth/outlook/return'
      preLoaderRoute: typeof OauthOutlookReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/teams/return': {
      id: '/oauth/teams/return'
      path: '/oauth/teams/return'
      fullPath: '/oauth/teams/return'
      preLoaderRoute: typeof OauthTeamsReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBenefitsRoute: typeof AuthenticatedBenefitsRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataTransferRoute: typeof AuthenticatedDataTransferRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedEntitiesRoute: typeof AuthenticatedEntitiesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHrAccountsRoute: typeof AuthenticatedHrAccountsRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrgRoute: typeof AuthenticatedOrgRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecruitmentRoute: typeof AuthenticatedRecruitmentRoute
  AuthenticatedSalaryRoute: typeof AuthenticatedSalaryRoute
  AuthenticatedSeparationRoute: typeof AuthenticatedSeparationRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTimesheetsRoute: typeof AuthenticatedTimesheetsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBenefitsRoute: AuthenticatedBenefitsRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataTransferRoute: AuthenticatedDataTransferRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedEntitiesRoute: AuthenticatedEntitiesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHrAccountsRoute: AuthenticatedHrAccountsRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrgRoute: AuthenticatedOrgRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecruitmentRoute: AuthenticatedRecruitmentRoute,
  AuthenticatedSalaryRoute: AuthenticatedSalaryRoute,
  AuthenticatedSeparationRoute: AuthenticatedSeparationRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTimesheetsRoute: AuthenticatedTimesheetsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RequestAccessRoute: RequestAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiActionableApprovalRoute: ApiActionableApprovalRoute,
  OauthOutlookReturnRoute: OauthOutlookReturnRoute,
  OauthTeamsReturnRoute: OauthTeamsReturnRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
